import { NextResponse } from "next/server";
import { SITE_URL } from "@/lib/site";

export async function GET() {
  // Modern AI crawler allowlist. These are the bots that actually drive
  // AI-search traffic (ChatGPT search, Perplexity, Claude, Google AI,
  // Anthropic web tooling, You.com, Brave, etc.). We want maximum surface
  // in AI search results for these.
  const aiCrawlers = [
    "GPTBot",
    "ChatGPT-User",
    "OAI-SearchBot",
    "ClaudeBot",
    "Claude-Web",
    "anthropic-ai",
    "PerplexityBot",
    "Perplexity-User",
    "Google-Extended",
    "GoogleOther",
    "Applebot-Extended",
    "DuckAssistBot",
    "YouBot",
  ];

  // Aggressive scraper-farm / SEO-audit bots that crawl thousands of URLs in
  // bursts and drive metered hosting cost with little to no SEO upside.
  // These are blocked outright; well-behaved ones honor Disallow.
  const throttledCrawlers = [
    "Bytespider",
    "CCBot",
    "Amazonbot",
    "DataForSeoBot",
    "SemrushBot",
    "AhrefsBot",
    "MJ12bot",
    "DotBot",
    "PetalBot",
  ];

  const aiCrawlerBlocks = aiCrawlers
    .map(
      (bot) => `User-Agent: ${bot}
Allow: /
`,
    )
    .join("\n");

  const throttledCrawlerBlocks = throttledCrawlers
    .map(
      (bot) => `User-Agent: ${bot}
Disallow: /
`,
    )
    .join("\n");

  const robotsTxt = `# robots.txt for ${SITE_URL}
# Generated by Next.js. Do not edit by hand.

User-Agent: *
Allow: /
Allow: /agents
Allow: /blog
Allow: /workflow
Allow: /tools
Allow: /projects/invobill
Disallow: /admin
Disallow: /api/admin
Disallow: /api/auth
Crawl-delay: 10

User-Agent: Googlebot
Allow: /

User-Agent: Bingbot
Allow: /

${aiCrawlerBlocks}
${throttledCrawlerBlocks}
Sitemap: ${SITE_URL}/sitemap.xml
Host: ${SITE_URL}

Content-Signal: ai-train=no, search=yes, ai-input=yes
`;

  return new NextResponse(robotsTxt, {
    headers: {
      "Content-Type": "text/plain",
      "Content-Signal": "ai-train=no, search=yes, ai-input=yes",
    },
  });
}
