import { NextResponse } from "next/server";
import { AGENTS_URL, SITE_URL } from "@/lib/site";

export async function GET() {
  // Modern AI crawler allowlist. These are the bots that actually drive
  // AI-search traffic (ChatGPT search, Perplexity, Claude, Google AI,
  // Anthropic web tooling, You.com, Brave, etc.). Block list intentionally
  // empty — we want maximum surface in AI search results.
  const aiCrawlers = [
    "GPTBot",
    "ChatGPT-User",
    "OAI-SearchBot",
    "ClaudeBot",
    "Claude-Web",
    "anthropic-ai",
    "PerplexityBot",
    "Perplexity-User",
    "Google-Extended",
    "GoogleOther",
    "Applebot-Extended",
    "Bytespider",
    "CCBot",
    "DuckAssistBot",
    "Amazonbot",
    "YouBot",
  ];

  const aiCrawlerBlocks = aiCrawlers
    .map(
      (bot) => `User-Agent: ${bot}
Allow: /
`,
    )
    .join("\n");

  const robotsTxt = `# robots.txt for ${SITE_URL}
# Generated by Next.js. Do not edit by hand.

User-Agent: *
Allow: /
Allow: /agents
Allow: /blog
Allow: /workflow
Disallow: /admin
Disallow: /api/admin
Disallow: /api/auth

User-Agent: Googlebot
Allow: /

User-Agent: Bingbot
Allow: /

${aiCrawlerBlocks}
Sitemap: ${SITE_URL}/sitemap.xml
Sitemap: ${AGENTS_URL}/sitemap.xml
Host: ${SITE_URL}

Content-Signal: ai-train=no, search=yes, ai-input=yes
`;

  return new NextResponse(robotsTxt, {
    headers: {
      "Content-Type": "text/plain",
      "Content-Signal": "ai-train=no, search=yes, ai-input=yes",
    },
  });
}
