import { NextResponse } from "next/server";
import { SITE_URL } from "@/lib/site";

export async function GET() {
  // Modern AI crawler allowlist. These are the bots that actually drive
  // AI-search traffic (ChatGPT search, Perplexity, Claude, Google AI,
  // Anthropic web tooling, You.com, Brave, etc.). We want maximum surface
  // in AI search results for these.
  const aiCrawlers = [
    "GPTBot",
    "ChatGPT-User",
    "OAI-SearchBot",
    "ClaudeBot",
    "Claude-Web",
    "anthropic-ai",
    "PerplexityBot",
    "Perplexity-User",
    "Google-Extended",
    "GoogleOther",
    "Applebot-Extended",
    "DuckAssistBot",
    "YouBot",
  ];

  // Aggressive scraper-farm / SEO-audit bots that crawl thousands of URLs in
  // bursts and drive metered hosting cost with little to no SEO upside.
  // These are blocked outright; well-behaved ones honor Disallow.
  const throttledCrawlers = [
    "Bytespider",
    "CCBot",
    "Amazonbot",
    "DataForSeoBot",
    "SemrushBot",
    "AhrefsBot",
    "MJ12bot",
    "DotBot",
    "PetalBot",
  ];

  // Paths that must never be crawled by anyone.
  //
  // These have to be repeated inside EVERY named user-agent group. robots.txt
  // is not additive: a crawler obeys only the single most-specific group that
  // matches it and ignores `User-Agent: *` entirely. Previously the named
  // Googlebot / Bingbot / AI-crawler groups contained only `Allow: /`, which
  // meant /admin and the auth endpoints were crawlable by exactly the bots we
  // care about most.
  const disallowedPaths = ["/admin", "/api/admin", "/api/auth"];

  const disallowBlock = disallowedPaths
    .map((path) => `Disallow: ${path}`)
    .join("\n");

  const aiCrawlerBlocks = aiCrawlers
    .map(
      (bot) => `User-Agent: ${bot}
Allow: /
${disallowBlock}
`,
    )
    .join("\n");

  const throttledCrawlerBlocks = throttledCrawlers
    .map(
      (bot) => `User-Agent: ${bot}
Disallow: /
`,
    )
    .join("\n");

  const robotsTxt = `# robots.txt for ${SITE_URL}
# Generated by Next.js. Do not edit by hand.

User-Agent: *
Allow: /
${disallowBlock}

User-Agent: Googlebot
Allow: /
${disallowBlock}

User-Agent: Bingbot
Allow: /
${disallowBlock}

${aiCrawlerBlocks}
${throttledCrawlerBlocks}
Sitemap: ${SITE_URL}/sitemap.xml

Content-Signal: ai-train=no, search=yes, ai-input=yes
`;

  return new NextResponse(robotsTxt, {
    headers: {
      "Content-Type": "text/plain",
      "Content-Signal": "ai-train=no, search=yes, ai-input=yes",
    },
  });
}
